package example.sigsam;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Holder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String value;

   public Holder()
   {
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public Holder(java.lang.String value)
   {
      this.value = value;
   }

}